BOW

N-GRAM

TFIDF

# Bag of Words

In [11]:
import numpy as np
import pandas as pd

In [12]:
corpus = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

corpus

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv = CountVectorizer()
bow = cv.fit_transform(corpus['text'])

In [21]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [23]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [27]:
print(bow[0].toarray()),
print(bow[1].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]


In [29]:
cv.transform(['Ring Ring Ringa, Ring Ring Ringa, Ringa Ringa Ringa Ri']).toarray()

array([[0, 0, 0, 0, 0]])

In [30]:
cv.transform(['People like to watch TV']).toarray()

array([[0, 0, 1, 1, 0]])

# N Grams


**uniGram**:    `ngram_range = (1,1) `

**biGram**:  `ngram_range = (2,2)`

**triGram**:   `ngram_range = (3,3)`





In [31]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range = (2,2))
bow = cv.fit_transform(df['text'])

In [33]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


# TF-IDF (Term frequency- Inverse document frequency)


In [34]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
bow = tfidf.fit_transform(df['text'])

In [36]:
print(tfidf.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [37]:
bow.toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [42]:
print(tfidf.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
